import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Import font Inter
const roboto = Roboto({
  variable: "--font-roboto", // Đặt biến CSS
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "TripC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

